//Party Data
global.party =
[
	{
		name: "Chris",
		spr: spr_player_d_run,
		lvl: 1,
		xp: 0,
		hp: 11,
		hpMax: 12,
		pp: 100,
		ppMax: 100,
		def: 1,
		spd: 1,
		wrath: 1,
		iq: 1,
		strength: 6,
		stunned: false,
		mutatedHand: false,
		itchy: false,
		itnum: 0,
		poisoned: false,
		ponum: 0,
		poison: "",
		blind: false,
		sleep: false,
		noNut: false,
		soreT: false,
		afo: false,
		offenseup: false,
		defdown: false,
		aftype: "",
		anum: 0,
		hyper: false,
		hynum: 0,
		magicBarrier: false,
		holdingPresent: false,
		sprites: { /*idle: sChrisU, down: sChrisU*/},
		actions: [global.actionLibrary.attack, 
				  global.actionLibrary.stenchB, global.actionLibrary.nukeB, global.actionLibrary.poisonO, 
				  global.actionLibrary.fixUpB, global.actionLibrary.cureO, global.actionLibrary.drainO,
				  global.actionLibrary.ftsio, global.actionLibrary.weathA, global.actionLibrary.offenseupA,
				  global.actionLibrary.teleport, global.actionLibrary.favorithingA]
	}
	,
	{
		name: "Michael",
		spr: sMichael,
		lvl: 1,
		xp: 0,
		hp: 10,
		hpMax: 12,
		pp: 0,
		ppMax: 0,
		def: 2,
		spd: 2,
		wrath: 2,
		iq: 2,
		strength: 4,
		stunned: false,
		mutatedHand: false,
		itchy: false,
		itnum: 0,
		poisoned: false,
		ponum: 0,
		poison: "",
		blind: false,
		sleep: false,
		noNut: false,
		soreT: false,
		afo: false,
		offenseup: false,
		defdown: false,
		aftype: "",
		anum: 0,
		hyper: false,
		hynum: 0,
		magicBarrier: false,
		holdingPresent: false,
		sprites: { /*idle: sChrisU, down: sChrisU*/},
		actions: [global.actionLibrary.attack]
	}
	,
	{
		name: "Violet",
		spr: Violet_front,
		lvl: 1,
		xp: 0,
		hp: 11,
		hpMax: 12,
		pp: 100,
		ppMax: 100,
		def: 1,
		spd: 1,
		wrath: 1,
		iq: 1,
		strength: 6,
		stunned: false,
		mutatedHand: false,
		itchy: false,
		itnum: 0,
		poisoned: false,
		ponum: 0,
		poison: "",
		blind: false,
		sleep: false,
		noNut: false,
		soreT: false,
		afo: false,
		offenseup: false,
		defdown: false,
		aftype: "",
		anum: 0,
		hyper: false,
		hynum: 0,
		magicBarrier: false,
		holdingPresent: false,
		sprites: { /*idle: Violet_front, down: Violet_front*/},
		actions: [global.actionLibrary.attack, global.actionLibrary.stenchA, global.actionLibrary.nukeA, global.actionLibrary.lightningA, 
				  global.actionLibrary.fixUpA, global.actionLibrary.cureA, global.actionLibrary.drainA,
				  global.actionLibrary.mutationA, global.actionLibrary.darknessA, global.actionLibrary.hyperA,
				  global.actionLibrary.teleport, global.actionLibrary.favorithingA]
	}
]


// Roster template for debug party manager

global.character_roster =
[
	{
		name: "Chris",
		spr: spr_player_d_run,
		lvl: 1,
		xp: 0,
		hp: 11,
		hpMax: 12,
		pp: 100,
		ppMax: 100,
		def: 1,
		spd: 1,
		wrath: 1,
		iq: 1,
		strength: 6,
		stunned: false,
		mutatedHand: false,
		itchy: false,
		itnum: 0,
		poisoned: false,
		ponum: 0,
		poison: "",
		blind: false,
		sleep: false,
		noNut: false,
		soreT: false,
		afo: false,
		offenseup: false,
		defdown: false,
		aftype: "",
		anum: 0,
		hyper: false,
		hynum: 0,
		magicBarrier: false,
		holdingPresent: false,
		sprites: { /*idle: sChrisU, down: sChrisU*/},
		actions: [global.actionLibrary.attack, 
				  global.actionLibrary.stenchB, global.actionLibrary.nukeB, global.actionLibrary.poisonO, 
				  global.actionLibrary.fixUpB, global.actionLibrary.cureO, global.actionLibrary.drainO,
				  global.actionLibrary.ftsio, global.actionLibrary.weathA, global.actionLibrary.offenseupA,
				  global.actionLibrary.teleport, global.actionLibrary.favorithingA]
	}
	,
	{
		name: "Michael",
		spr: sMichael,
		lvl: 1,
		xp: 0,
		hp: 10,
		hpMax: 12,
		pp: 0,
		ppMax: 0,
		def: 2,
		spd: 2,
		wrath: 2,
		iq: 2,
		strength: 4,
		stunned: false,
		mutatedHand: false,
		itchy: false,
		itnum: 0,
		poisoned: false,
		ponum: 0,
		poison: "",
		blind: false,
		sleep: false,
		noNut: false,
		soreT: false,
		afo: false,
		offenseup: false,
		defdown: false,
		aftype: "",
		anum: 0,
		hyper: false,
		hynum: 0,
		magicBarrier: false,
		holdingPresent: false,
		sprites: { /*idle: sChrisU, down: sChrisU*/},
		actions: [global.actionLibrary.attack]
	}
	,
	{
		name: "Violet",
		spr: Violet_front,
		lvl: 1,
		xp: 0,
		hp: 11,
		hpMax: 12,
		pp: 100,
		ppMax: 100,
		def: 1,
		spd: 1,
		wrath: 1,
		iq: 1,
		strength: 6,
		stunned: false,
		mutatedHand: false,
		itchy: false,
		itnum: 0,
		poisoned: false,
		ponum: 0,
		poison: "",
		blind: false,
		sleep: false,
		noNut: false,
		soreT: false,
		afo: false,
		offenseup: false,
		defdown: false,
		aftype: "",
		anum: 0,
		hyper: false,
		hynum: 0,
		magicBarrier: false,
		holdingPresent: false,
		sprites: { /*idle: Violet_front, down: Violet_front*/},
		actions: [global.actionLibrary.attack, global.actionLibrary.stenchA, global.actionLibrary.nukeA, global.actionLibrary.lightningA, 
				  global.actionLibrary.fixUpA, global.actionLibrary.cureA, global.actionLibrary.drainA,
				  global.actionLibrary.mutationA, global.actionLibrary.darknessA, global.actionLibrary.hyperA,
				  global.actionLibrary.teleport, global.actionLibrary.favorithingA]
	}
]

